services:
  dev:
    build: devapp/.
  notes:
    build: notes/.

  apache:
    build: apache/.
    links:
      - notes
      - dev
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - 8000:80
